-- A type is a collection of related values.
-- basic types: Bool, Char, String, Int, Integer, Float, Double
-- List types, Tuple types, Function types, Curried functions, Polymorphic types, Overloaded types
--
-- basic classes: Eq, Ord, Show, Read, Num, Integral, Fractional
